apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-db-deploy
  labels:
    app: lms-db-deployment
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-api-db
  template:
    metadata:
      labels:
        app: lms-api-db
    spec:
      containers:
        - name: postgres-lms
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata          
          envFrom:
          - configMapRef:
              name: lms-dbconfig

      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: lms-db-claim
