
apiVersion: v1
kind: Service
metadata:
  name: lms-db-service
  labels:
    app: lms-postgres-service
spec:
  type: ClusterIP
  selector:
    app: lms-api-db
  ports:
    - port: 9911
      targetPort: 5432
